package com.icteam.loyalty.model.template;

import com.icteam.loyalty.model.Dictionary;
import com.icteam.loyalty.model.interfaces.ELanguage;
import com.icteam.loyalty.model.interfaces.EWhereClause;
import com.icteam.loyalty.model.interfaces.Where;

// Generated 3-mar-2011 9.42.28 by Hibernate Tools 3.4.0.CR1

/**
 * Dictionary generated by hbm2java
 */
public class DictionaryTemplate extends AbstractTemplate<Dictionary> {

    @Where
    private String kKey;

    @Where
    private ELanguage language;

    @Where(EWhereClause.LIKE_IGNORE_CASE)
    private String value;

    /**
     * @return il valore della variabile kKey di tipo PsiType:String.
     */
    public String getkKey() {
        return kKey;
    }

    /**
     * Setter per la variabile kKey.
     *
     * @param kKey
     *            il valore da assegnare alla variabile di tipo PsiType:String.
     */
    public void setkKey(String kKey) {
        this.kKey = kKey;
    }

    /**
     * @return il valore della variabile language di tipo PsiType:ELanguage.
     */
    public ELanguage getLanguage() {
        return language;
    }

    /**
     * Setter per la variabile language.
     *
     * @param language
     *            il valore da assegnare alla variabile di tipo PsiType:ELanguage.
     */
    public void setLanguage(ELanguage language) {
        this.language = language;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public String toString() {
        return "DictionaryTemplate ["
                + (kKey != null ? "kKey=" + kKey + ", " : "")
                + (language != null ? "language=" + language + ", " : "")
                + (value != null ? "value=" + value : "")
                + "]";
    }

}
